### ISSUE TITLE
FE: Linux packaged release

### ISSUE THREAD

**Issue by brendan-pike** [ZL-Audio/ZLRelease#1]
Would really love a Linux release of some sort also to avoid having to self-compile

Wonderful work, thank you!

**Comment by zsliu98** [comment]
Hi! This repo is built for people who cannot access github (I sync this repo to another website). Since you can access github, please directly download them from the corresponding repo, e.g., https://github.com/ZL-Audio/ZLEqualizer/releases .

**Comment by brendan-pike** [comment]
Thank you very much! :)
